{% set version = "0.4.3" %}
{% set sha256 = "27564e6cff53333593578bf4966c1aed82f0d9a71c204baa9fa907b6a48e13c6" %}

package:
  name: xpdconf
  version: {{ version }}

source:
  url: https://github.com/xpdAcq/xpdConf/releases/download/{{ version }}/xpdConf-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyyaml
    - databroker

test:
  imports:
    - xpdconf

about:
  license_file: LICENSE
  summary: Configuration manager for XPD beamlines
