{% set name = "xpdConf" %}
{% set version = "0.4.3" %}
{% set sha256 = "b3795b20a85b23fec4c55382211f51e668c0123501c111086d007518794ffe89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - databroker
    - pyyaml

test:
  imports:
    - xpdconf
  commands:
    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("xpdconf", "examples/sim.yaml"))'

about:
  home: https://github.com/xpdAcq/xpdConf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Configuration manager for XPD beamlines
  dev_url: https://github.com/xpdAcq/xpdConf
  doc_url: http://xpdacq.github.io
