{% set version = "0.4.1" %}
{% set sha256 = "2a1ca83ac3351180eea04df0c5c6e0e3b8fb7d0bf954215edf07f0621f56143a" %}

package:
  name: xpdconf
  version: {{ version }}

source:
  url: https://github.com/xpdAcq/xpdConf/releases/download/{{ version }}/xpdConf-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyyaml
    - databroker

test:
  imports:
    - xpdconf

about:
  license_file: LICENSE
  summary: Configuration manager for XPD beamlines
